export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";



export const USER_MANAGE_LOADING = "USER_MANAGE_LOADING";
export const USER_MANAGE_SUCCESS = "USER_MANAGE_SUCCESS";
export const USER_MANAGE_ERROR = "USER_MANAGE_ERROR";




export const USER_MANAGE_LOADING1 = "USER_MANAGE_LOADING1";
export const USER_MANAGE_SUCCESS1 = "USER_MANAGE_SUCCESS1";
export const USER_MANAGE_ERROR1 = "USER_MANAGE_ERROR1";


export const USER_MANAGE_LOADING12 = "USER_MANAGE_LOADING12";
export const USER_MANAGE_SUCCESS12 = "USER_MANAGE_SUCCESS12";
export const USER_MANAGE_ERROR12 = "USER_MANAGE_ERROR12";


export const USER_MANAGE_LOADING123 = "USER_MANAGE_LOADING123";
export const USER_MANAGE_SUCCESS123 = "USER_MANAGE_SUCCESS123";
export const USER_MANAGE_ERROR123 = "USER_MANAGE_ERROR123";